name: clone workflow
env:
  SECRET_HOST: ${{ secrets.HOST }}
  SECRET_NAME: ${{ secrets.USERNAME }}
  SECRET_PASS: ${{ secrets.PASSWORD }}
  SECRET_PORT: ${{ secrets.PORT }}
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: SECRET_HOST
          username: SECRET_NAME
          password : SECRET_PASS
          port: SECRET_PORT
          script: |
            cd ..
            cd pub/
            cd mlopez122.github.io
            git clone https://github.com/mlopez122/mlopez122.github.io.git
